# Generated by Django 3.1 on 2020-08-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_pizza_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='published',
            field=models.NullBooleanField(),
        ),
    ]
