# Generated by Django 3.1 on 2020-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_pizza_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='published',
            field=models.BooleanField(null=True),
        ),
    ]
